### ISSUE TITLE
Skip Travis Builds on Certain Changes

### ISSUE THREAD

**Issue by mmedal** [L33T-KR3W/soundcasts-server#22]
You don't want to run builds on every change (it's true, Scott). I'd say we could skip a travis build on things like the _README_, the _Procfile_, the _.editorconfig_, etc...

See: [Travis Docs](http://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build)

**Comment by mmedal** [comment]
nothing to implement here, it's in the commit message. just offering a conversation piece

**Comment by scott113341** [comment]
I can see not wanting to run a 10x10 build matrix for Angular.js that takes 15 hours if you're changing the readme, but I could also see you wanting to run it at the same time. I think it's bad practice to allow any contributor to arbitrarily skip CI builds using commit messages. The proper way to do this would be to configure the Travis yml file to skip builds if only certain files are changed so that acceptable CI skips would be documented: https://github.com/travis-ci/travis-ci/issues/1468

**Comment by mmedal** [comment]
That's why it's a case by case basis where only maintainers accept and merge pull requests. Closing due to n00b.
